name: Release

on:
    push:
        tags:
            - v*
    workflow_dispatch:

<<<<<<< HEAD
permissions: write-all
=======
permissions:
    contents: write
>>>>>>> upstream/main

jobs:
    release:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]
                include:
                    - os: macos-latest
                      platform: mac
                    - os: ubuntu-latest
                      platform: linux
                    - os: windows-latest
                      platform: windows

        steps:
            - uses: actions/checkout@v4
            - uses: oven-sh/setup-bun@v2

            - name: Install dependencies
<<<<<<< HEAD
              run: pnpm install --no-frozen-lockfile
=======
              run: bun install
>>>>>>> upstream/main

            - name: Build
              run: bun run build

            - name: Run Electron Builder
              if: ${{ matrix.platform != 'mac' }}
              run: |
                  bun run electron-builder --${{ matrix.platform }} --publish always
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Run Electron Builder
              if: ${{ matrix.platform == 'mac' }}
              run: |
<<<<<<< HEAD
                  pnpm electron-builder --${{ matrix.platform }} --publish always
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
=======
                  bun run electron-builder --${{ matrix.platform }} --publish always
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

>>>>>>> upstream/main
